=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/ladspa-swh.dtd
<!ELEMENT ladspa (global+,plugin+)>
<!ATTLIST ladspa version CDATA "1.0">

<!ELEMENT global (meta+,code?,p*)>

<!ELEMENT meta EMPTY>
<!ATTLIST meta name  (maker|copyright|properties) #REQUIRED
               value CDATA                        #REQUIRED>

<!ELEMENT code (#PCDATA)>

<!ELEMENT p (#PCDATA)>

<!ELEMENT plugin (name,p*,callback+,port+,instance-data*)>
<!ATTLIST plugin label CDATA #REQUIRED
                 id    CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT callback (#PCDATA)>
<!ATTLIST callback event (run|instatiate|activate|cleanup) #REQUIRED>

<!ELEMENT port (name, range*, p*)>
<!ATTLIST port label CDATA           #REQUIRED
               dir   (input|output)  #REQUIRED
               type  (audio|control) #REQUIRED>

<!ELEMENT range EMPTY>
<!ATTLIST range min CDATA #REQUIRED
                max CDATA #REQUIRED>

<!ELEMENT instance-data EMPTY>
<!ATTLIST instance-data label CDATA #REQUIRED
                        type  CDATA #REQUIRED>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/tape_delay_1211.xml
<?xml version="1.0" ?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css" ?>
<ladspa>
	<global>
		<meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
		<meta name="copyright" value="GPL"/>
		<code><![CDATA[
#include "ladspa-util.h"

#define BASE_BUFFER 8 // Tape length (inches)
		]]></code>
	</global>

	<plugin label="tapeDelay" id="1211" class="DelayPlugin,SimulatorPlugin">
		<name>Tape Delay Simulation</name>
                <p>Correctly models the tape motion and some of the smear effect, there is no simulation for the head saturation yet, as I don't have a good model of it. When I get one I will add it.</p>
                <p>The way the tape accelerates and decelerates gives a nicer delay effect for many purposes.</p>

		<callback event="instantiate"><![CDATA[
			unsigned int mbs = BASE_BUFFER * s_rate;
			sample_rate = s_rate;
			for (buffer_size = 4096; buffer_size < mbs;
			     buffer_size *= 2);
			buffer = malloc(buffer_size * sizeof(LADSPA_Data));
			buffer_mask = buffer_size - 1;
			phase = 0;
			last_phase = 0;
			last_in = 0.0f;
			last2_in = 0.0f;
			last3_in = 0.0f;
			z0 = 0.0f;
			z1 = 0.0f;
			z2 = 0.0f;
		]]></callback>

		<callback event="activate">
			int i;

			for (i = 0; i &lt; buffer_size; i++) {
				buffer[i] = 0;
			}
			phase = 0;
			last_phase = 0;
			last_in = 0.0f;
			last2_in = 0.0f;
			last3_in = 0.0f;
			z0 = 0.0f;
			z1 = 0.0f;
			z2 = 0.0f;
		</callback>

		<callback event="cleanup"><![CDATA[
			free(plugin_data->buffer);
		]]></callback>

		<callback event="run"><![CDATA[
unsigned int pos;
float increment = f_clamp(speed, 0.0f, 40.0f);
float lin_int, lin_inc;
unsigned int track;
unsigned int fph;
LADSPA_Data out;

const float da = DB_CO(da_db);
const float t1a = DB_CO(t1a_db);
const float t2a = DB_CO(t2a_db);
const float t3a = DB_CO(t3a_db);
const float t4a = DB_CO(t4a_db);
const unsigned int t1d_s = f_round(t1d * sample_rate);
const unsigned int t2d_s = f_round(t2d * sample_rate);
const unsigned int t3d_s = f_round(t3d * sample_rate);
const unsigned int t4d_s = f_round(t4d * sample_rate);

for (pos = 0; pos < sample_count; pos++) {
	fph = f_trunc(phase);
	last_phase = fph;
	lin_int = phase - (float)fph;

	out = buffer[(unsigned int)(fph - t1d_s) & buffer_mask] * t1a;
	out += buffer[(unsigned int)(fph - t2d_s) & buffer_mask] * t2a;
	out += buffer[(unsigned int)(fph - t3d_s) & buffer_mask] * t3a;
	out += buffer[(unsigned int)(fph - t4d_s) & buffer_mask] * t4a;

	phase += increment;
	lin_inc = 1.0f / (floor(phase) - last_phase + 1);
	lin_inc = lin_inc > 1.0f ? 1.0f : lin_inc;
	lin_int = 0.0f;
	for (track = last_phase; track < phase; track++) {
		lin_int += lin_inc;
		buffer[track & buffer_mask] =
		 cube_interp(lin_int, last3_in, last2_in, last_in, input[pos]);
	}
	last3_in = last2_in;
	last2_in = last_in;
	last_in = input[pos];
	out += input[pos] * da;
	buffer_write(output[pos], out);
	if (phase >= buffer_size) {
		phase -= buffer_size;
	}
}

// Store current phase in instance
plugin_data->phase = phase;
plugin_data->last_phase = last_phase;
plugin_data->last_in = last_in;
plugin_data->last2_in = last2_in;
plugin_data->last3_in = last3_in;
plugin_data->z0 = z0;
plugin_data->z1 = z1;
plugin_data->z2 = z2;
		]]></callback>

		<port label="speed" dir="input" type="control" hint="default_1">
			<name>Tape speed (inches/sec, 1=normal)</name>
			<range min="0" max="10"/>
		</port>

		<port label="da_db" dir="input" type="control" hint="default_minimum">
			<name>Dry level (dB)</name>
			<range min="-90" max="0"/>
		</port>

		<port label="t1d" dir="input" type="control" hint="default_0">
			<name>Tap 1 distance (inches)</name>
			<range min="0" max="4"/>
		</port>

		<port label="t1a_db" dir="input" type="control" hint="default_0">
			<name>Tap 1 level (dB)</name>
			<range min="-90" max="0"/>
		</port>

		<port label="t2d" dir="input" type="control" hint="default_low">
			<name>Tap 2 distance (inches)</name>
			<range min="0" max="4"/>
		</port>

		<port label="t2a_db" dir="input" type="control" hint="default_minimum">
			<name>Tap 2 level (dB)</name>
			<range min="-90" max="0"/>
		</port>

		<port label="t3d" dir="input" type="control" hint="default_middle">
			<name>Tap 3 distance (inches)</name>
			<range min="0" max="4"/>
		</port>

		<port label="t3a_db" dir="input" type="control" hint="default_minimum">
			<name>Tap 3 level (dB)</name>
			<range min="-90" max="0"/>
		</port>

		<port label="t4d" dir="input" type="control" hint="default_high">
			<name>Tap 4 distance (inches)</name>
			<range min="0" max="4"/>
		</port>

		<port label="t4a_db" dir="input" type="control" hint="default_minimum">
			<name>Tap 4 level (dB)</name>
			<range min="-90" max="0"/>
		</port>

		<port label="input" dir="input" type="audio">
			<name>Input</name>
		</port>

		<port label="output" dir="output" type="audio">
			<name>Output</name>
		</port>

		<instance-data label="buffer" type="LADSPA_Data *"/>
		<instance-data label="buffer_size" type="unsigned int"/>
		<instance-data label="buffer_mask" type="unsigned int"/>
		<instance-data label="phase" type="float"/>
		<instance-data label="last_phase" type="unsigned int"/>
		<instance-data label="last_in" type="LADSPA_Data"/>
		<instance-data label="last2_in" type="LADSPA_Data"/>
		<instance-data label="last3_in" type="LADSPA_Data"/>
		<instance-data label="sample_rate" type="int"/>
                <instance-data label="z0" type="LADSPA_Data"/>
                <instance-data label="z1" type="LADSPA_Data"/>
                <instance-data label="z2" type="LADSPA_Data"/>
	</plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/harmonic_gen_1220.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #define HARMONICS 11

      /* Calculate Chebychev coefficents from partial magnitudes, adapted from
       * example in Num. Rec. */
      void chebpc(float c[], float d[])
      {
          int k, j;
          float sv, dd[HARMONICS];
      
          for (j = 0; j < HARMONICS; j++) {
              d[j] = dd[j] = 0.0;
          }
      
          d[0] = c[HARMONICS - 1];
      
          for (j = HARMONICS - 2; j >= 1; j--) {
              for (k = HARMONICS - j; k >= 1; k--) {
                  sv = d[k];
                  d[k] = 2.0 * d[k - 1] - dd[k];
                  dd[k] = sv;
              }
              sv = d[0];
              d[0] = -dd[0] + c[j];
              dd[0] = sv;
          }
      
          for (j = HARMONICS - 1; j >= 1; j--) {
              d[j] = d[j - 1] - dd[j];
          }
          d[0] = -dd[0] + 0.5 * c[0];
      }
    ]]></code>
  </global>

  <plugin label="harmonicGen" id="1220" class="GeneratorPlugin">
    <name>Harmonic generator</name>
    <p>\subsubsection{What does it do?}</p>
    <p>Allows you to add harmonics and remove the fundamental from any audio signal.</p>
    <p>\subsubsection{Known bugs}</p>
    <p>There is no bandwith limiting filter on the output, so it is easy to create excessively high frequency harmonics that could cause aliasing problems. In practice this doesn't seem to be a serious problem however.</p>
    <p>\subsubsection{Examples}</p>
    <p>There are many interesting effects you can achieve with sinewaves, one example is producing bandlimited squarewaves from sinewaves. To do this set the parameters to 1, 0, -0.3333, 0, 0.2, 0, -0.14285, 0, 0.11111.</p>
    <p>To get a triangle like signal use 1, 0, -0.3333, 0, -0.2, 0, -0.14285, 0, -0.11111.</p>

    <callback event="activate"><![CDATA[
      itm1 = 0.0f;
      otm1 = 0.0f;
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos, i;
      float mag_fix;
      float mag[HARMONICS] = {0.0f, mag_1, mag_2, mag_3, mag_4, mag_5, mag_6,
                              mag_7, mag_8, mag_9, mag_10};
      float p[HARMONICS];

      // Normalise magnitudes
      mag_fix = (fabs(mag_1) + fabs(mag_2) + fabs(mag_3) + fabs(mag_4) +
                 fabs(mag_5) + fabs(mag_6) + fabs(mag_7) + fabs(mag_8) +
                 fabs(mag_9) + fabs(mag_10));
      if (mag_fix < 1.0f) {
        mag_fix = 1.0f;
      } else {
        mag_fix = 1.0f / mag_fix;
      }
      for (i=0; i<HARMONICS; i++) {
        mag[i] *= mag_fix;
      }

      // Calculate polynomial coefficients, using Chebychev aproximation
      chebpc(mag, p);

      for (pos = 0; pos < sample_count; pos++) {
        float x = input[pos], y;

        // Calculate the polynomial using Horner's Rule
	y = p[0] + (p[1] + (p[2] + (p[3] + (p[4] + (p[5] + (p[6] + (p[7] +
            (p[8] + (p[9] + p[10] * x) * x) * x) * x) * x) * x) * x) * x) *
            x) * x;

	// DC offset remove (odd harmonics cause DC offset)
        otm1 = 0.999f * otm1 + y - itm1;
        itm1 = y;

        buffer_write(output[pos], otm1);
      }

      plugin_data->itm1 = itm1;
      plugin_data->otm1 = otm1;
    ]]></callback>

    <port label="mag_1" dir="input" type="control" hint="default_1">
      <name>Fundamental magnitude</name>
      <p>The amplitude of the fundamental of the signal, reduce it to 0 to remove the base signal altogether, or -1 to phase invert it.</p>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_2" dir="input" type="control" hint="default_0">
      <name>2nd harmonic magnitude</name>
      <p>The 2nd harmonic, its frequency is twice the frequency of the fundamental.</p>
      <p>Even harmonics add a distorted feel to the sound, valve (tube) amplifiers introduce distortions at all the harmonics.</p>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_3" dir="input" type="control" hint="default_0">
      <name>3rd harmonic magnitude</name>
      <p>The 3rd harmonic, its frequency is three times the frequency of the fundamental.</p>
      <p>Transistor amplifiers only introduce distortion into the odd harmonics.</p>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_4" dir="input" type="control" hint="default_0">
      <name>4th harmonic magnitude</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_5" dir="input" type="control" hint="default_0">
      <name>5th harmonic magnitude</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_6" dir="input" type="control" hint="default_0">
      <name>6th harmonic magnitude</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_7" dir="input" type="control" hint="default_0">
      <name>7th harmonic magnitude</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_8" dir="input" type="control" hint="default_0">
      <name>8th harmonic magnitude</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_9" dir="input" type="control" hint="default_0">
      <name>9th harmonic magnitude</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="mag_10" dir="input" type="control" hint="default_0">
      <name>10th harmonic magnitude</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
      <range min="-1" max="+1"/>
    </port>

    <port label="output" dir="output" type="audio">
      <name>Output</name>
      <range min="-1" max="+1"/>
    </port>

    <instance-data label="itm1" type="float" />
    <instance-data label="otm1" type="float" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/sc2_1426.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #include "util/db.h"
      #include "util/rms.h"

      #define A_TBL 256
    ]]></code>
  </global>

  <plugin label="sc2" id="1426" class="CompressorPlugin">
    <name>SC2</name>
    <p>A compressor with sidechain. Based on the code for SC1.</p>

    <callback event="instantiate"><![CDATA[
      unsigned int i;
      float sample_rate = (float)s_rate;

      rms = rms_env_new();
      sum = 0.0f;
      amp = 0.0f;
      gain = 0.0f;
      gain_t = 0.0f;
      env = 0.0f;
      count = 0;

      as = malloc(A_TBL * sizeof(float));
      as[0] = 1.0f;
      for (i=1; i<A_TBL; i++) {
	as[i] = expf(-1.0f / (sample_rate * (float)i / (float)A_TBL));
      }

      db_init();
    ]]></callback>

    <callback event="cleanup"><![CDATA[
      rms_env_free(plugin_data->rms);
      free(plugin_data->as);
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;

      const float ga = as[f_round(attack * 0.001f * (float)(A_TBL-1))];
      const float gr = as[f_round(release * 0.001f * (float)(A_TBL-1))];
      const float rs = (ratio - 1.0f) / ratio;
      const float mug = db2lin(makeup_gain);
      const float knee_min = db2lin(threshold - knee);
      const float knee_max = db2lin(threshold + knee);
      const float ef_a = ga * 0.25f;
      const float ef_ai = 1.0f - ef_a;

      for (pos = 0; pos < sample_count; pos++) {
        sum += sidechain[pos] * sidechain[pos];

        if (amp > env) {
          env = env * ga + amp * (1.0f - ga);
        } else {
          env = env * gr + amp * (1.0f - gr);
        }
        if (count++ % 4 == 3) {
          amp = rms_env_process(rms, sum * 0.25f);
          sum = 0.0f;
          if (env <= knee_min) {
            gain_t = 1.0f;
	  } else if (env < knee_max) {
	    const float x = -(threshold - knee - lin2db(env)) / knee;
	    gain_t = db2lin(-knee * rs * x * x * 0.25f);
          } else {
            gain_t = db2lin((threshold - lin2db(env)) * rs);
          }
        }
        gain = gain * ef_a + gain_t * ef_ai;
        buffer_write(output[pos], input[pos] * gain * mug);
      }
      plugin_data->sum = sum;
      plugin_data->amp = amp;
      plugin_data->gain = gain;
      plugin_data->gain_t = gain_t;
      plugin_data->env = env;
      plugin_data->count = count;
    ]]></callback>

    <port label="attack" dir="input" type="control" hint="default_low">
      <name>Attack time (ms)</name>
      <p>The attack time in milliseconds.</p>
      <range min="2" max="400"/>
    </port>

    <port label="release" dir="input" type="control" hint="default_middle">
      <name>Release time (ms)</name>
      <p>The release time in milliseconds.</p>
      <range min="2" max="800"/>
    </port>

    <port label="threshold" dir="input" type="control" hint="default_maximum">
      <name>Threshold level (dB)</name>
      <p>The point at which the compressor will start to kick in.</p>
      <range min="-30" max="0"/>
    </port>

    <port label="ratio" dir="input" type="control" hint="default_1">
      <name>Ratio (1:n)</name>
      <p>The gain reduction ratio used when the signal level exceeds the threshold.</p>
      <range min="1" max="10"/>
    </port>

    <port label="knee" dir="input" type="control" hint="default_low">
      <name>Knee radius (dB)</name>
      <p>The distance from the threshold where the knee curve starts.</p>
      <range min="1" max="10"/>
    </port>

    <port label="makeup_gain" dir="input" type="control" hint="default_0">
      <name>Makeup gain (dB)</name>
      <p>Controls the gain of the makeup input signal in dB's.</p>
      <range min="0" max="+24"/>
    </port>

    <port label="sidechain" dir="input" type="audio">
      <name>Sidechain</name>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="output" dir="output" type="audio">
      <name>Output</name>
    </port>

    <instance-data label="rms" type="rms_env *" />
    <instance-data label="as" type="float *" />

    <instance-data label="sum" type="float" />
    <instance-data label="amp" type="float" />
    <instance-data label="gain" type="float" />
    <instance-data label="gain_t" type="float" />
    <instance-data label="env" type="float" />
    <instance-data label="count" type="unsigned int" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/gate_1410.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #include "ladspa-util.h"
      #include "util/biquad.h"

      #define ENV_TR 0.0001f

      #define CLOSED  1
      #define OPENING 2
      #define OPEN    3
      #define CLOSING 4
    ]]></code>
  </global>

  <plugin label="gate" id="1410" class="GatePlugin">
    <name>Gate</name>
    <p>The parameters are copied from the Drawmer DS-201, but I've never used one, so if someone out there has one, please tell me if it behaves differently.</p>

    <callback event="instantiate"><![CDATA[
      fs = s_rate;
      env = 0.0f;
      gate = 0.0f;
      state = CLOSED;
      hold_count = 0;

      lf = malloc(sizeof(biquad));
      hf = malloc(sizeof(biquad));
      biquad_init(lf);
      biquad_init(hf);
    ]]></callback>

    <callback event="activate"><![CDATA[
      env = 0.0f;
      gate = 0.0f;
      state = CLOSED;
      biquad_init(lf);
      biquad_init(hf);
    ]]></callback>

    <callback event="cleanup"><![CDATA[
      free(plugin_data->lf);
      free(plugin_data->hf);
    ]]></callback>


    <callback event="run"><![CDATA[
      unsigned long pos;
      float cut = DB_CO(range);
      float t_level = DB_CO(threshold);
      float a_rate = 1000.0f / (attack * fs);
      float d_rate = 1000.0f / (decay * fs);
      float post_filter, apost_filter;
      int op = f_round(select);

      ls_set_params(lf, lf_fc, -40.0f, 0.6f, fs);
      hs_set_params(hf, hf_fc, -50.0f, 0.6f, fs);

      for (pos = 0; pos < sample_count; pos++) {
	post_filter = biquad_run(lf, input[pos]);
	post_filter = biquad_run(hf, post_filter);
	apost_filter = fabs(post_filter);

        if (apost_filter > env) {
          env = apost_filter;
        } else {
          env = apost_filter * ENV_TR + env * (1.0f - ENV_TR);
        }

	if (state == CLOSED) {
	  if (env >= t_level) {
	    state = OPENING;
	  }
        } else if (state == OPENING) {
	  gate += a_rate;
	  if (gate >= 1.0f) {
	    gate = 1.0f;
	    state = OPEN;
	    hold_count = f_round(hold * fs * 0.001f);
	    plugin_data->hold_count = hold_count;
	  }
        } else if (state == OPEN) {
	  if (hold_count <= 0) {
	    if (env < t_level) {
	      state = CLOSING;
            }
	  } else {
	    hold_count--;
	  }
	} else if (state == CLOSING) {
	  gate -= d_rate;
	  if (env >= t_level) {
	    state = OPENING;
	  } else if (gate <= 0.0f) {
	    gate = 0.0f;
	    state = CLOSED;
	  }
	}

	if (op == 0) {
          buffer_write(output[pos], input[pos] * (cut * (1.0f - gate) + gate));
	} else if (op == -1) {
          buffer_write(output[pos], post_filter);
	} else {
	  buffer_write(output[pos], input[pos]);
	}
      }

      plugin_data->env = env;
      plugin_data->gate = gate;
      plugin_data->state = state;
      plugin_data->hold_count = hold_count;
    ]]></callback>

    <port label="lf_fc" dir="input" type="control" hint="sample_rate,default_minimum">
      <name>LF key filter (Hz)</name>
      <p>Controls the cutoff of the low frequency filter (highpass).</p>
      <range min="0.0007f" max="0.1"/>
    </port>

    <port label="hf_fc" dir="input" type="control" hint="sample_rate,default_maximum">
      <name>HF key filter (Hz)</name>
      <p>Controls the cutoff of the high frequency filter (lowpass).</p>
      <range min="0.005f" max="0.49"/>
    </port>

    <port label="threshold" dir="input" type="control" hint="default_minimum">
      <name>Threshold (dB)</name>
      <p>Controls the level at which the gate will open.</p>
      <range min="-70" max="+20"/>
    </port>

    <port label="attack" dir="input" type="control" hint="default_low">
      <name>Attack (ms)</name>
      <p>Controls the time the gate will take to open fully.</p>
      <range min="0.01" max="1000"/>
    </port>

    <port label="hold" dir="input" type="control" hint="default_high">
      <name>Hold (ms)</name>
      <p>Controls the minimum time the gate will stay open for.</p>
      <range min="2" max="2000"/>
    </port>

    <port label="decay" dir="input" type="control" hint="default_middle">
      <name>Decay (ms)</name>
      <p>Controls the time the gate will take to close fully.</p>
      <range min="2" max="4000"/>
    </port>

    <port label="range" dir="input" type="control" hint="default_minimum">
      <name>Range (dB)</name>
      <p>Controls the difference between the gate's open and closed state.</p>
      <range min="-90" max="0"/>
    </port>

    <port label="select" dir="input" type="control" hint="integer,default_0">
      <name>Output select (-1 = key listen, 0 = gate, 1 = bypass)</name>
      <p>Controls output monitor. -1 is the output of the key filters (so you can check what is being gated on). 0 is the normal, gated output. 1 is bypass mode.</p>
      <range min="-1" max="1"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="output" dir="output" type="audio">
      <name>Output</name>
    </port>

    <instance-data label="fs" type="float" />
    <instance-data label="env" type="float" />
    <instance-data label="gate" type="float" />
    <instance-data label="state" type="int" />
    <instance-data label="hold_count" type="int" />
    <instance-data label="lf" type="biquad *" />
    <instance-data label="hf" type="biquad *" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/freq_tracker_1418.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #include "ladspa-util.h"
    ]]></code>
  </global>

  <plugin label="freqTracker" id="1418" class="FrequencyMeterPlugin">
    <name>Frequency tracker</name>

    <callback event="instantiate"><![CDATA[
      fs = s_rate;
      f = 0.0f;
      fo = 0.0f;
      cross_time = 0;
      last_amp = 0.0f;
    ]]></callback>

    <callback event="activate"><![CDATA[
      cross_time = 0;
      f = 0.0f;
      fo = 0.0f;
      last_amp = 0.0f;
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;
      float xm1 = last_amp;
      const float damp_lp = (1.0f - speed) * 0.9f;
      const float damp_lpi = 1.0f - damp_lp;

      for (pos = 0; pos < sample_count; pos++) {
	if (input[pos] < 0.0f && xm1 > 0.0f) {
	  if (cross_time > 3.0f) {
	    f = fs / ((float)cross_time * 2.0f);
	  }
	  cross_time = 0;
	}
	xm1 = input[pos];
	cross_time++;
	fo = fo * damp_lp + f * damp_lpi;
	fo = flush_to_zero(fo);
	buffer_write(freq[pos], fo);
      }

      plugin_data->last_amp = xm1;
      plugin_data->fo = fo;
      plugin_data->f = f;
      plugin_data->cross_time = cross_time;
    ]]></callback>

    <port label="speed" dir="input" type="control" hint="default_middle">
      <name>Tracking speed</name>
      <p>This controls the level of damping applied to the output.</p>
      <p>High values will make the frequency output jump around, low values will make it a bit slow to respond.</p>
      <range min="0" max="1"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="freq" dir="output" type="audio">
      <name>Frequency (Hz)</name>
    </port>

    <instance-data label="fs" type="float" />
    <instance-data label="cross_time" type="int" />
    <instance-data label="last_amp" type="LADSPA_Data" />
    <instance-data label="f" type="LADSPA_Data" />
    <instance-data label="fo" type="LADSPA_Data" />
  </plugin>
</ladspa>
