=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/ladspa-swh.dtd
<!ELEMENT ladspa (global+,plugin+)>
<!ATTLIST ladspa version CDATA "1.0">

<!ELEMENT global (meta+,code?,p*)>

<!ELEMENT meta EMPTY>
<!ATTLIST meta name  (maker|copyright|properties) #REQUIRED
               value CDATA                        #REQUIRED>

<!ELEMENT code (#PCDATA)>

<!ELEMENT p (#PCDATA)>

<!ELEMENT plugin (name,p*,callback+,port+,instance-data*)>
<!ATTLIST plugin label CDATA #REQUIRED
                 id    CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT callback (#PCDATA)>
<!ATTLIST callback event (run|instatiate|activate|cleanup) #REQUIRED>

<!ELEMENT port (name, range*, p*)>
<!ATTLIST port label CDATA           #REQUIRED
               dir   (input|output)  #REQUIRED
               type  (audio|control) #REQUIRED>

<!ELEMENT range EMPTY>
<!ATTLIST range min CDATA #REQUIRED
                max CDATA #REQUIRED>

<!ELEMENT instance-data EMPTY>
<!ATTLIST instance-data label CDATA #REQUIRED
                        type  CDATA #REQUIRED>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/delayorama_1402.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <code><![CDATA[
      #include <ladspa-util.h>

      #define MIN(a,b) ((a) < (b) ? (a) : (b))
      #define N_TAPS 128

      typedef struct {
        unsigned int delay;
        float gain;
      } tap;
    ]]></code>
  </global>

  <plugin label="delayorama" id="1402" class="DelayPlugin">
    <name>Delayorama</name>

    <callback event="instantiate"><![CDATA[
      sample_rate = s_rate;

      buffer_pos = 0;

      buffer_size = 6.0f * sample_rate;

      taps = malloc(2 * sizeof(tap *));
      taps[0] = calloc(N_TAPS, sizeof(tap));
      taps[1] = calloc(N_TAPS, sizeof(tap));
      active_set = 0;
      next_set = 1;

      buffer = calloc(buffer_size, sizeof(LADSPA_Data));

      last_out = 0.0f;

      last_ampsc = 0.0f;
      last_delaysc = 0.0f;
      last_start = 0;
      last_range = 0;
      last_ntaps = 0;
      last_seed = 0;
      last_a_rand = 0;
      last_d_rand = 0;
    ]]></callback>

    <callback event="activate"><![CDATA[
      memset(buffer, 0, buffer_size * sizeof(LADSPA_Data));

      last_out = 0.0f;
      last_ampsc = 0.0f;
      last_delaysc = 0.0f;
      last_start = 0;
      last_range = 0;
      last_ntaps = 0;
      last_seed = 0;
      last_a_rand = 0;
      last_d_rand = 0;
    ]]></callback>

    <callback event="cleanup"><![CDATA[
      free(plugin_data->taps[0]);
      free(plugin_data->taps[1]);
      free(plugin_data->taps);
      free(plugin_data->buffer);
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;
      float coef = DB_CO(gain);
      unsigned int i;
      unsigned int recalc = 0;
      unsigned int ntaps = LIMIT(f_round(tap_count), 2, N_TAPS);
      float range = f_clamp(delay_range * sample_rate, 0.0f,
				(float)(buffer_size-1));
      LADSPA_Data out;
      float xfade = 0.0f;

      const float feedback = feedback_pc * 0.01f;
      const float gain_rand = gain_rand_pc * 0.01f;
      const float delay_rand = delay_rand_pc * 0.01f;


      if (ntaps != last_ntaps) {
        recalc = 1;
        plugin_data->last_ntaps = ntaps;
      }
      if (first_delay != last_start) {
        recalc = 1;
        plugin_data->last_start = first_delay;
      }
      if (range != last_range) {
        recalc = 1;
        plugin_data->last_range = range;
      }
      if (delay_scale != last_delaysc) {
        recalc = 1;
        plugin_data->last_delaysc = delay_scale;
      }
      if (gain_scale != last_ampsc) {
        recalc = 1;
        plugin_data->last_ampsc = gain_scale;
      }
      if (seed != last_seed) {
        recalc = 1;
        plugin_data->last_seed = seed;
      }
      if (gain_rand != last_a_rand) {
        recalc = 1;
        plugin_data->last_a_rand = gain_rand;
      }
      if (delay_rand != last_d_rand) {
        recalc = 1;
        plugin_data->last_d_rand = delay_rand;
      }

      if (recalc) {
        float delay_base = first_delay * sample_rate;
        float delay_fix;
        float gain, delay, delay_sum;
	float d_rand, g_rand;

	srand(f_round(seed));
        if (delay_base + range > buffer_size-1) {
          delay_base = buffer_size - 1 - range;
        }

	if (gain_scale <= 1.0f) {
          gain = 1.0f;
	} else {
          gain = 1.0f / pow(gain_scale, ntaps-1);
        }

	if (delay_scale == 1.0f) {
		delay_fix = range / (ntaps - 1);
	} else {
		delay_fix = range * (delay_scale - 1.0f) / (pow(delay_scale, ntaps - 1) - 1.0f);
	}
        delay = 1.0f;
	delay_sum = 0.0f;

        for (i=0; i<ntaps; i++) {
	  g_rand = (1.0f-gain_rand) + (float)rand() / (float)RAND_MAX * 2.0f * gain_rand;
	  d_rand = (1.0f-delay_rand) + (float)rand() / (float)RAND_MAX * 2.0f * delay_rand;
          taps[next_set][i].delay = MIN((unsigned int)(delay_base + delay_sum * delay_fix * d_rand), buffer_size-1);
          taps[next_set][i].gain = gain * g_rand;

          delay_sum += delay;
          delay *= delay_scale;
	  gain *= gain_scale;
        }
        for (; i<N_TAPS; i++) {
	  taps[next_set][i].delay = 0.0f;
	  taps[next_set][i].gain = 0.0f;
        }
      }

      out = last_out;
      for (pos = 0; pos < sample_count; pos++) {
        buffer[buffer_pos] = input[pos] * coef + (out * feedback);

        out = 0.0f;
        for (i=0; i<ntaps; i++) {
          int p = buffer_pos - taps[active_set][i].delay;
          if (p<0) p += buffer_size;
          out += buffer[p] * taps[active_set][i].gain;
        }

        if (recalc) {
	  xfade += 1.0f / (float)sample_count;
          out *= (1-xfade);
          for (i=0; i<ntaps; i++) {
            int p = buffer_pos - taps[next_set][i].delay;
            if (p<0) p += buffer_size;
            out += buffer[p] * taps[next_set][i].gain * xfade;
          }
        }

        buffer_write(output[pos], LIN_INTERP(wet, input[pos], out));

	if (++buffer_pos >= buffer_size) {
          buffer_pos = 0;
        }
      }

      if (recalc) {
	plugin_data->active_set = next_set;
	plugin_data->next_set = active_set;
      }

      plugin_data->buffer_pos = buffer_pos;
      plugin_data->last_out = out;
    ]]></callback>

    <port label="seed" dir="input" type="control" hint="integer,default_0">
      <name>Random seed</name>
      <p>Controls the random numbers that will be used to stagger the delays and amplitudes if random is turned up on them. Changing this forces the random values to be recalulated.</p>
      <range min="0" max="1000"/>
    </port>

    <port label="gain" dir="input" type="control" hint="default_0">
      <name>Input gain (dB)</name>
      <p>Controls the gain of the input signal in dB's.</p>
      <range min="-96" max="+24"/>
    </port>

    <port label="feedback_pc" dir="input" type="control" hint="default_0">
      <name>Feedback (%)</name>
      <p>Controls the amount of output signal fed back into the input.</p>
      <range min="0" max="100"/>
    </port>

    <port label="tap_count" dir="input" type="control" hint="integer,default_minimum">
      <name>Number of taps</name>
      <p>Controls the number of taps in the delay.</p>
      <range min="2" max="N_TAPS"/>
    </port>

    <port label="first_delay" dir="input" type="control" hint="default_0">
      <name>First delay (s)</name>
      <p>The time of the first delay.</p>
      <range min="0" max="5"/>
    </port>

    <port label="delay_range" dir="input" type="control" hint="default_maximum">
      <name>Delay range (s)</name>
      <p>The time difference between the first and last delay.</p>
      <range min="0.0001" max="6"/>
    </port>

    <port label="delay_scale" dir="input" type="control" hint="default_1">
      <name>Delay change</name>
      <p>The scaling factor between one delay and the next.</p>
      <range min="0.2" max="5"/>
    </port>

    <port label="delay_rand_pc" dir="input" type="control" hint="default_0">
      <name>Delay random (%)</name>
      <p>The random factor applied to the delay.</p>
      <range min="0" max="100"/>
    </port>

    <port label="gain_scale" dir="input" type="control" hint="default_1">
      <name>Amplitude change</name>
      <p>The scaling factor between one amplitude and the next.</p>
      <range min="0.2" max="5"/>
    </port>

    <port label="gain_rand_pc" dir="input" type="control" hint="default_0">
      <name>Amplitude random (%)</name>
      <p>The random factor applied to the amplitude.</p>
      <range min="0" max="100"/>
    </port>

    <port label="wet" dir="input" type="control" hint="default_1">
      <name>Dry/wet mix</name>
      <p>The level of delayed sound mixed into the output.</p>
      <range min="0" max="1"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="output" dir="output" type="audio">
      <name>Output</name>
    </port>

    <instance-data label="buffer_pos" type="unsigned long"/>
    <instance-data label="buffer_size" type="unsigned int"/>
    <instance-data label="sample_rate" type="unsigned int"/>
    <instance-data label="last_start" type="float"/>
    <instance-data label="last_range" type="float"/>
    <instance-data label="last_delaysc" type="float"/>
    <instance-data label="last_ampsc" type="float"/>
    <instance-data label="last_ntaps" type="unsigned int"/>
    <instance-data label="last_seed" type="float"/>
    <instance-data label="last_a_rand" type="float"/>
    <instance-data label="last_d_rand" type="float"/>
    <instance-data label="last_out" type="LADSPA_Data"/>
    <instance-data label="active_set" type="unsigned int"/>
    <instance-data label="next_set" type="unsigned int"/>
    <instance-data label="taps" type="tap **"/>
    <instance-data label="buffer" type="LADSPA_Data *"/>
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/zm1_1428.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
  </global>

  <plugin label="zm1" id="1428" class="UtilityPlugin">
    <name>z-1</name>
    <p>A plugin that implements the $z^{-1}$ function (a single sample delay).</p>

    <callback event="instantiate"><![CDATA[
      xm1 = 0.0f;
    ]]></callback>

    <callback event="activate"><![CDATA[
      xm1 = 0.0f;
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;
      LADSPA_Data tmp;

      for (pos = 0; pos < sample_count; pos++) {
	tmp = input[pos];
        buffer_write(output[pos], xm1);
	xm1 = tmp;
      }
      plugin_data->xm1 = xm1;
    ]]></callback>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="output" dir="output" type="audio">
      <name>Output</name>
    </port>

    <instance-data label="xm1" type="LADSPA_Data" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/pitch_scale_1194.xml
<?xml version="1.0" ?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css" ?>
<ladspa>
	<global>
		<meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
		<meta name="copyright" value="GPL"/>
		<meta name="properties" value="HARD_RT_CAPABLE"/>
		<code>
			#include "util/pitchscale.h"

			#define FRAME_LENGTH 4096
			#define OVER_SAMP    16
		</code>
	</global>

	<plugin label="pitchScaleHQ" id="1194" class="PitchPlugin">
		<name>Higher Quality Pitch Scaler</name>
                <p>A pitch shifter implementation that scales the harmonics appropriately with the base frequencies. It is an implementation of Stephen M. Sprengler's pitch scaler design. It gives reasonable, general purpose results for small changes, but won't give Antares or Eventide anything to worry about.</p>
		<p>The FFT block size and oversampling has been kept at reasonable levels to keep the CPU usage low, but it is smoother than the other Pitch Scaler.</p>

		<callback event="run">
			pitch_scale(buffers, mult, FRAME_LENGTH, OVER_SAMP, sample_count, sample_rate, input, output, RUN_ADDING, run_adding_gain);
			*(plugin_data->latency) = FRAME_LENGTH - (FRAME_LENGTH
							/ OVER_SAMP);
		</callback>

		<callback event="instantiate">
			int i;
			float arg;

			buffers = malloc(sizeof(sbuffers));
			sample_rate = s_rate;
			buffers->gInFIFO = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gOutFIFO = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gLastPhase = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gSumPhase = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gOutputAccum = malloc(2*FRAME_LENGTH * sizeof(float));
			buffers->gAnaFreq = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gAnaMagn = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gSynFreq = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gSynMagn = malloc(FRAME_LENGTH * sizeof(float));
			buffers->gWindow = malloc(FRAME_LENGTH * sizeof(float));

			arg = 2.0f * M_PI / (float)(FRAME_LENGTH-1);
			for (i=0; i &lt; FRAME_LENGTH; i++) {
				// Blackman-Harris
				buffers->gWindow[i] =  0.35875f - 0.48829f * cos(arg * (float)i) + 0.14128f * cos(2.0f * arg * (float)i) - 0.01168f * cos(3.0f * arg * (float)i);
				// Gain correction
				buffers->gWindow[i] *= 0.761f;

			}

		</callback>

		<callback event="activate"><![CDATA[
			memset(buffers->gInFIFO, 0, FRAME_LENGTH*sizeof(float));
			memset(buffers->gOutFIFO, 0, FRAME_LENGTH*sizeof(float));
			memset(buffers->gLastPhase, 0, FRAME_LENGTH*sizeof(float)/2);
			memset(buffers->gSumPhase, 0, FRAME_LENGTH*sizeof(float)/2);
			memset(buffers->gOutputAccum, 0, 2*FRAME_LENGTH*sizeof(float));
			memset(buffers->gAnaFreq, 0, FRAME_LENGTH*sizeof(float));
			memset(buffers->gAnaMagn, 0, FRAME_LENGTH*sizeof(float));
			buffers->gRover = 0;
			pitch_scale(buffers, 1.0, FRAME_LENGTH, 16, FRAME_LENGTH, sample_rate, buffers->gInFIFO, buffers->gOutFIFO, 0, 0.0f);
		]]></callback>

		<callback event="cleanup"><![CDATA[
                        free (plugin_data->buffers->gInFIFO);
                        free (plugin_data->buffers->gOutFIFO);
                        free (plugin_data->buffers->gLastPhase);
                        free (plugin_data->buffers->gSumPhase);
                        free (plugin_data->buffers->gOutputAccum);
                        free (plugin_data->buffers->gAnaFreq);
                        free (plugin_data->buffers->gAnaMagn);
                        free (plugin_data->buffers->gSynFreq);
                        free (plugin_data->buffers->gSynMagn);
                        free (plugin_data->buffers->gWindow);
                        free (plugin_data->buffers);
		]]></callback>

		<port label="mult" dir="input" type="control" hint="default_1">
			<name>Pitch co-efficient</name>
			<range min="0.5" max="2"/>
			<p>The pitch scaling factor, a value of 2.0 will increase the pitch by one octave, etc.</p>
		</port>

		<port label="input" dir="input" type="audio">
			<name>Input</name>
		</port>

		<port label="output" dir="output" type="audio">
			<name>Output</name>
		</port>

		<port label="latency" dir="output" type="control">
			<name>latency</name>
		</port>

		<instance-data label="buffers" type="sbuffers *"/>

		<instance-data label="sample_rate" type="long"/>
	</plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/debug_1184.xml
<?xml version="1.0" ?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css" ?>
<ladspa>
	<global>
		<meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
		<meta name="copyright" value="GPL"/>
		<meta name="properties" value="HARD_RT_CAPABLE"/>
		<code>
			#include "stdio.h"
		</code>
	</global>

	<plugin label="debug" id="1184" class="UtilityPlugin">
		<name>Debug Plugin</name>
		<p>Prints some stats about the input stream to stdout. Not intended for general use.</p>

		<callback event="instantiate">
			printf("sample rate %ld\n", s_rate);
		</callback>

		<callback event="run">
			static LADSPA_Data max, min, maxl, minl;
			unsigned long pos;

			if (reset) {
				max = 0;
				min = 0;
				maxl = 0;
				minl = 1;
			}

			for (pos = 0; pos &lt; sample_count; pos++) {
				if (allvals) {
					printf("%f\n", input[pos]);
				}
				max = fabs(input[pos]) &gt; max?fabs(input[pos]):max;
				min = fabs(input[pos]) &lt; min?fabs(input[pos]):min;
				maxl = input[pos] &gt; maxl?input[pos]:maxl;
				minl = input[pos] &lt; minl?input[pos]:minl;
				buffer_write(output[pos], input[pos]);
			}
			printf("amplitude (%f, %f)\t", min, max);
			printf("level (%f, %f)\n", minl, maxl);
		</callback>

		<port label="allvals" dir="input" type="control">
			<name>Diplay all values?</name>
			<range min="0" max="1"/>
		</port>

		<port label="reset" dir="input" type="control">
			<name>Reset counters?</name>
			<range min="0" max="1"/>
		</port>

		<port label="input" dir="input" type="audio">
			<name>Input</name>
		</port>

		<port label="output" dir="output" type="audio">
			<name>Output</name>
		</port>
	</plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/gverb_1216.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Juhana Sadeharju &lt;kouhia at nic.funet.fi&gt;, LADSPAification by Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code>
/*

GVerb algorithm designed and implemented by Juhana Sadeharju.
LADSPA implementation and GVerb speeds ups by Steve Harris.

Comments and suggestions should be mailed to Juhana Sadeharju
(kouhia at nic funet fi).

*/

#include "ladspa-util.h"
#include "gverb/gverbdsp.h"
#include "gverb/gverb.h"
    </code>
  </global>

  <plugin label="gverb" id="1216" class="ReverbPlugin">
    <name>GVerb</name>
    <p>A mono in, stereo out reverb implementation by Juhana Sadeharju (kouhia at nic.funet.fi). I ported it to LADSPA and did some testing.</p>
    <p>Please contact Juhana directly regarding any bugs you find.</p>
    <p><![CDATA[
      Paul Winkler recommends a good starting point for a "large hall" as follows:

	\begin{tabular}{|l|r|}
	\hline
	Parameter & Value \\
	\hline
	Roomsize & 200 \\
	Reverb time & 1.3 \\
	Damping & 0.4 \\
	Input bandwidth & 0.5 \\
	Dry signal level & 0 \\
	Early reflection level & -12 \\
	Tail level & 0 \\
	\hline
	\end{tabular}
    ]]></p>

    <callback event="instantiate"><![CDATA[
      verb = gverb_new(s_rate, 300.0f, 50.0f, 7.0f, 0.5f, 15.0f, 0.5f, 0.5f, 0.5f);
    ]]></callback>

    <callback event="activate"><![CDATA[
      gverb_flush(plugin_data->verb);
    ]]></callback>

    <callback event="cleanup"><![CDATA[
      gverb_free(plugin_data->verb);
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;
      float l, r;
      float dryc = DB_CO(drylevel);

      gverb_set_roomsize(verb, roomsize);
      gverb_set_revtime(verb, revtime);
      gverb_set_damping(verb, damping);
      gverb_set_inputbandwidth(verb, inputbandwidth);
      gverb_set_earlylevel(verb, DB_CO(earlylevel));
      gverb_set_taillevel(verb, DB_CO(taillevel));

      for (pos = 0; pos < sample_count; pos++) {
        gverb_do(verb, input[pos], &l, &r);
        buffer_write(outl[pos], l + input[pos] * dryc);
        buffer_write(outr[pos], r + input[pos] * dryc);
      }
    ]]></callback>

    <port label="roomsize" dir="input" type="control" hint="default_low">
      <name>Roomsize (m)</name>
      <p>The size of the room, in meters. Excessivly large, and excessivly small values will make it sound a bit unrealistic.</p>
      <p>Values of around 30 sound good.</p>
      <range min="1" max="300"/>
    </port>

    <port label="revtime" dir="input" type="control" hint="default_low">
      <name>Reverb time (s)</name>
      <p>Reverb decay time, in seconds. 7 is a good place to start.</p>
      <range min="0.1" max="30"/>
    </port>

    <port label="damping" dir="input" type="control" hint="default_middle">
      <name>Damping</name>
      <p>This controls the high frequency damping (a lowpass filter), values near 1 will make it sound very bright, values near 0 will make it sound very dark.</p>
      <range min="0" max="1"/>
    </port>

    <port label="inputbandwidth" dir="input" type="control" hint="default_high">
      <name>Input bandwidth</name>
      <p>This is like a damping control for the input, it has a similar effect to the damping control, but is subtly different.</p>
      <range min="0" max="1"/>
    </port>

    <port label="drylevel" dir="input" type="control" hint="default_minimum">
      <name>Dry signal level (dB)</name>
      <p>The amount of dry signal to be mixed with the reverberated signal.</p>
      <range min="-70" max="0"/>
    </port>

    <port label="earlylevel" dir="input" type="control" hint="default_0">
      <name>Early reflection level (dB)</name>
      <p>The quantity of early reflections (scatter reflections directly from the source). Think of Lexicons ambiance patches.</p>
      <range min="-70" max="0"/>
    </port>

    <port label="taillevel" dir="input" type="control" hint="default_high">
      <name>Tail level (dB)</name>
      <p>The level of the classic reverb tail reflections.</p>
      <range min="-70" max="0"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="outl" dir="output" type="audio">
      <name>Left output</name>
    </port>

    <port label="outr" dir="output" type="audio">
      <name>Right output</name>
    </port>

    <instance-data label="verb" type="ty_gverb *" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/plate_1423.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code>
      #include "util/waveguide_nl.h"

      #define LP_INNER 0.96f
      #define LP_OUTER 0.983f

      #define RUN_WG(n, junct_a, junct_b) waveguide_nl_process_lin(w[n], junct_a - out[n*2+1], junct_b - out[n*2], out+n*2, out+n*2+1)
    </code>
  </global>

  <plugin label="plate" id="1423" class="ReverbPlugin">
    <name>Plate reverb</name>
    <p>A physical model of a steel plate reverb.</p>
    <p>Based on Josep Comajuncosas' gong model, it uses 8 linear waveguides to model the plate.</p>

    <callback event="instantiate"><![CDATA[
      w = malloc(8 * sizeof(waveguide_nl *));
      w[0] = waveguide_nl_new(2389, LP_INNER, 0.04f, 0.0f);
      w[1] = waveguide_nl_new(4742, LP_INNER, 0.17f, 0.0f);
      w[2] = waveguide_nl_new(4623, LP_INNER, 0.52f, 0.0f);
      w[3] = waveguide_nl_new(2142, LP_INNER, 0.48f, 0.0f);
      w[4] = waveguide_nl_new(5597, LP_OUTER, 0.32f, 0.0f);
      w[5] = waveguide_nl_new(3692, LP_OUTER, 0.89f, 0.0f);
      w[6] = waveguide_nl_new(5611, LP_OUTER, 0.28f, 0.0f);
      w[7] = waveguide_nl_new(3703, LP_OUTER, 0.29f, 0.0f);

      out = calloc(32, sizeof(float));
    ]]></callback>

    <callback event="activate"><![CDATA[
      unsigned int i;

      for (i = 0; i < 8; i++) {
	waveguide_nl_reset(w[i]);
      }
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;
      const float scale = powf(time * 0.117647f, 1.34f);
      const float lpscale = 1.0f - damping * 0.93;

      for (pos=0; pos<8; pos++) {
	waveguide_nl_set_delay(w[pos], w[pos]->size * scale);
      }
      for (pos=0; pos<4; pos++) {
	waveguide_nl_set_fc(w[pos], LP_INNER * lpscale);
      }
      for (; pos<8; pos++) {
	waveguide_nl_set_fc(w[pos], LP_OUTER * lpscale);
      }

      for (pos = 0; pos < sample_count; pos++) {
	const float alpha = (out[0] + out[2] + out[4] + out[6]) * 0.5f
			    + input[pos];
	const float beta = (out[1] + out[9] + out[14]) * 0.666666666f;
	const float gamma = (out[3] + out[8] + out[11]) * 0.666666666f;
	const float delta = (out[5] + out[10] + out[13]) * 0.666666666f;
	const float epsilon = (out[7] + out[12] + out[15]) * 0.666666666f;

	RUN_WG(0, beta, alpha);
	RUN_WG(1, gamma, alpha);
	RUN_WG(2, delta, alpha);
	RUN_WG(3, epsilon, alpha);
	RUN_WG(4, beta, gamma);
	RUN_WG(5, gamma, delta);
	RUN_WG(6, delta, epsilon);
	RUN_WG(7, epsilon, beta);

        buffer_write(outputl[pos], beta * wet + input[pos] * (1.0f - wet));
        buffer_write(outputr[pos], gamma * wet + input[pos] * (1.0f - wet));
      }
    ]]></callback>

    <callback event="cleanup"><![CDATA[
      unsigned int i;

      for (i = 0; i < 8; i++) {
	waveguide_nl_free(plugin_data->w[i]);
      }
      free(plugin_data->w);
      free(plugin_data->out);
    ]]></callback>

    <port label="time" dir="input" type="control" hint="default_middle">
      <name>Reverb time</name>
      <p>Controls the RT60 time of the reverb. Actually controls the size of the plate. The mapping between plate size and RT60 time is just a heuristic, so it's not very accurate.</p>
      <range min="0.01" max="8.5"/>
    </port>

    <port label="damping" dir="input" type="control" hint="default_low">
      <name>Damping</name>
      <p>Controls the degree that the surface of the plate is damped.</p>
      <range min="0" max="1"/>
    </port>

    <port label="wet" dir="input" type="control" hint="default_low">
      <name>Dry/wet mix</name>
      <p>Controls the balance between the dry and wet signals.</p>
      <range min="0" max="1"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="outputl" dir="output" type="audio">
      <name>Left output</name>
    </port>

    <port label="outputr" dir="output" type="audio">
      <name>Right output</name>
    </port>

    <instance-data label="w" type="waveguide_nl **" />
    <instance-data label="out" type="float *" />
  </plugin>
</ladspa>
