=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/ladspa-swh.dtd
<!ELEMENT ladspa (global+,plugin+)>
<!ATTLIST ladspa version CDATA "1.0">

<!ELEMENT global (meta+,code?,p*)>

<!ELEMENT meta EMPTY>
<!ATTLIST meta name  (maker|copyright|properties) #REQUIRED
               value CDATA                        #REQUIRED>

<!ELEMENT code (#PCDATA)>

<!ELEMENT p (#PCDATA)>

<!ELEMENT plugin (name,p*,callback+,port+,instance-data*)>
<!ATTLIST plugin label CDATA #REQUIRED
                 id    CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT callback (#PCDATA)>
<!ATTLIST callback event (run|instatiate|activate|cleanup) #REQUIRED>

<!ELEMENT port (name, range*, p*)>
<!ATTLIST port label CDATA           #REQUIRED
               dir   (input|output)  #REQUIRED
               type  (audio|control) #REQUIRED>

<!ELEMENT range EMPTY>
<!ATTLIST range min CDATA #REQUIRED
                max CDATA #REQUIRED>

<!ELEMENT instance-data EMPTY>
<!ATTLIST instance-data label CDATA #REQUIRED
                        type  CDATA #REQUIRED>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/divider_1186.xml
<?xml version="1.0" ?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css" ?>
<ladspa>
	<global>
		<meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
		<meta name="copyright" value="GPL"/>
		<meta name="properties" value="HARD_RT_CAPABLE"/>
	</global>

	<plugin label="divider" id="1186" class="GeneratorPlugin">
		<name>Audio Divider (Suboctave Generator)</name>
		<p>Reduces the period of the signal by the factor given, and makes it a square wave in the process. Has some amplitude tracking capability, but not really useful on complex signals.</p>

		<callback event="instantiate"><![CDATA[
out = 1.0f;
amp = 0.0f;
count = 0.0f;
lamp = 0.0f;
last = 0.0f;
zeroxs = 0;
		]]></callback>

		<callback event="run"><![CDATA[
/* Integer version of denominator */
int den = (int)denominator;

unsigned long pos;

for (pos = 0; pos < sample_count; pos++) {
	count += 1.0f;
	if ((input[pos] > 0.0f && last <= 0.0f) ||
	 (input[pos] < 0.0f && last >= 0.0)) {
		zeroxs++;
		if (den == 1) {
			out = out > 0.0f ? -1.0f : 1.0f;
			lamp = amp / count;
			zeroxs = 0;
			count = 0;
			amp = 0;
		}
	}
	amp += fabs(input[pos]);
	if (den > 1 && (zeroxs % den) == den-1) {
		out = out > 0.0f ? -1.0f : 1.0f;
		lamp = amp / count;
		zeroxs = 0;
		count = 0;
		amp = 0;
	}
	last = input[pos];
	buffer_write(output[pos], out * lamp);
}

plugin_data->last = last;
plugin_data->amp = amp;
plugin_data->lamp = lamp;
plugin_data->zeroxs = zeroxs;
plugin_data->count = count;
plugin_data->out = out;
		]]></callback>

		<port label="denominator" dir="input" type="control" hint="integer,default_1">
			<name>Denominator</name>
			<range min="1" max="8"/>
			<p>The factor the incoming frequency will be divided by.</p>
		</port>

		<port label="input" dir="input" type="audio">
			<name>Input</name>
		</port>

		<port label="output" dir="output" type="audio">
			<name>Output</name>
			<range min="-1" max="+1"/>
		</port>

		<!-- Last input value, to find 0 crossings -->
		<instance-data label="last" type="LADSPA_Data"/>

		<!-- Current amplitude sum (well, amp of last half cycle) -->
		<instance-data label="amp" type="LADSPA_Data"/>

		<!-- Average last amplitude (well, amp of last half cycle) -->
		<instance-data label="lamp" type="LADSPA_Data"/>

		<!-- Count of zero xings to make divider -->
		<instance-data label="zeroxs" type="int"/>

		<!-- Count of number of samples since x -->
		<instance-data label="count" type="float"/>

		<!-- Current output value -->
		<instance-data label="out" type="LADSPA_Data"/>
	</plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/impulse_1885.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Andy Wingo &lt;wingo at pobox dot com&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #include "ladspa-util.h"

      #define LOG001 -6.9077552789f
    ]]></code>
  </global>

  <!-- ******   IMPULSE-FC   ****** -->

  <plugin label="impulse_fc" id="1885" class="UtilityPlugin">
    <name>Nonbandlimited single-sample impulses (Frequency: Control)</name>
    <p>Based on work by James McCartney in SuperCollider.</p>
    
    <callback event="instantiate"><![CDATA[
      sample_rate = s_rate;
      phase = 0.f;
    ]]></callback>
    
    <callback event="activate"><![CDATA[
      phase = 0.f;
    ]]></callback>
    
    <callback event="run"><![CDATA[
      int i;
      float phase_step = frequency / sample_rate;

      for (i=0; i<sample_count; i++) {
        if (phase > 1.f) {
          phase -= 1.f;
          buffer_write(out[i], 1.f);
        } else {
          buffer_write(out[i], 0.f);
        }
        phase += phase_step;
      }

      plugin_data->phase = phase;
    ]]></callback>

    <port label="frequency" dir="input" type="control" hint="default_1">
      <name>Frequency (Hz)</name>
      <range min="0"/>
      <p>
       Frequency for the impulses.
      </p>
    </port>

    <port label="out" dir="output" type="audio">
      <name>Output</name>
    </port>

    <instance-data label="sample_rate" type="LADSPA_Data" />
    <instance-data label="phase" type="float" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/declip_1195.xml
<?xml version="1.0" ?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css" ?>
<ladspa>
	<global>
		<meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
		<meta name="copyright" value="GPL"/>
		<meta name="properties" value="HARD_RT_CAPABLE"/>
		<code>
			#define MAX_AMP 1.0f
			#define CLIP 0.8f
			#define CLIP_A ((MAX_AMP - CLIP) * (MAX_AMP - CLIP))
			#define CLIP_B (MAX_AMP - 2.0f * CLIP)
		</code>
	</global>

	<plugin label="declip" id="1195" class="WaveshaperPlugin">
		<name>Declipper</name>
		<p>Removes nasty clicks from input signals, not very kind to them though.</p>
		<p>This code came from the music-dsp mailing list, but it was unattributed, if it's yours, please drop me a line and I'll credit you.</p>

		<callback event="run"><![CDATA[
			unsigned long pos;

			for (pos = 0; pos < sample_count; pos++) {
				const LADSPA_Data in = input[pos];

				if((in < CLIP) && (in > -CLIP)) {
					buffer_write(output[pos], in);
				} else if (in > 0.0f) {
					buffer_write(output[pos], MAX_AMP - (CLIP_A / (CLIP_B + in)));
				} else {
					buffer_write(output[pos], -(MAX_AMP - (CLIP_A / (CLIP_B - in))));
				}
			}
		]]></callback>

		<port label="input" dir="input" type="audio">
			<name>Input</name>
			<range min="-1" max="+1"/>
		</port>

		<port label="output" dir="output" type="audio">
			<name>Output</name>
			<range min="-1" max="+1"/>
		</port>
	</plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/valve_1209.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #include "ladspa-util.h"
    ]]></code>
  </global>

  <plugin label="valve" id="1209" class="DistortionPlugin,SimulatorPlugin">
    <name>Valve saturation</name>
    <p>A model of valve (tube) distortion, lacking some of the harmonics you would get in a real tube amp, but sounds good nonetheless.</p>
    <p>Taken from Ragnar Bendiksen's thesis: \url{https://web.archive.org/web/20050212034404/http://www.notam02.no/~rbendiks/Diplom/Innhold.html}.</p>

    <callback event="activate"><![CDATA[
      itm1 = 0.0f;
      otm1 = 0.0f;
    ]]></callback>

    <callback event="run"><![CDATA[
unsigned long pos;
LADSPA_Data fx;

const float q = q_p - 0.999f;
const float dist = dist_p * 40.0f + 0.1f;

if (q == 0.0f) {
	for (pos = 0; pos < sample_count; pos++) {
		if (input[pos] == q) {
			fx = 1.0f / dist;
		} else {
			fx = input[pos] / (1.0f - f_exp(-dist * input[pos]));
		}
		otm1 = 0.999f * otm1 + fx - itm1;
		round_to_zero(&otm1);
		itm1 = fx;
		buffer_write(output[pos], otm1);
	}
} else {
	for (pos = 0; pos < sample_count; pos++) {
		if (input[pos] == q) {
			fx = 1.0f / dist + q / (1.0f - f_exp(dist * q));
		} else {
			fx = (input[pos] - q) /
			 (1.0f - f_exp(-dist * (input[pos] - q))) +
			 q / (1.0f - f_exp(dist * q));
		}
		otm1 = 0.999f * otm1 + fx - itm1;
		round_to_zero(&otm1);
		itm1 = fx;
		buffer_write(output[pos], otm1);
	}
}

plugin_data->itm1 = itm1;
plugin_data->otm1 = otm1;
    ]]></callback>

    <port label="q_p" dir="input" type="control" hint="default_0">
      <name>Distortion level</name>
      <p>How hard the signal is driven against the limit of the amplifier.</p>
      <range min="0" max="1"/>
    </port>

    <port label="dist_p" dir="input" type="control" hint="default_0">
      <name>Distortion character</name>
      <p>The hardness of the sound, low for soft, high for hard.</p>
      <range min="0" max="1"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="output" dir="output" type="audio">
      <name>Output</name>
    </port>

    <instance-data label="itm1" type="LADSPA_Data"/>
    <instance-data label="otm1" type="LADSPA_Data"/>

  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/satan_maximiser_1408.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #include <math.h>
      #include "ladspa-util.h"

      #define BUFFER_SIZE 16
      #define BUFFER_MASK 15
    ]]></code>
  </global>

  <plugin label="satanMaximiser" id="1408" class="DynamicsPlugin,DistortionPlugin">
    <name>Barry's Satan Maximiser</name>
    <p>Formerly Stupid Compressor. Thanks to Matt Yee-King for the name.</p>
    <p>Compresses signals with a stupidly short attack and decay, infinite
ratio and hard knee. Not really as a compressor, but good harsh (non-musical)
distortion.</p>

    <callback event="instantiate"><![CDATA[
      env = 0.0f;
      buffer = malloc(sizeof(LADSPA_Data) * BUFFER_SIZE);
      buffer_pos = 0;
    ]]></callback>

    <callback event="activate"><![CDATA[
      env = 0.0f;
      memset(buffer, 0, sizeof(LADSPA_Data) * BUFFER_SIZE);
      buffer_pos = 0;
    ]]></callback>

    <callback event="cleanup"><![CDATA[
      free(plugin_data->buffer);
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;
      int delay;
      float env_tr, env_sc, knee;
      float env_time = env_time_p;

      if (env_time < 2.0f) {
	env_time = 2.0f;
      }
      knee = DB_CO(knee_point);
      delay = f_round(env_time * 0.5f);
      env_tr = 1.0f / env_time;

      for (pos = 0; pos < sample_count; pos++) {
	if (fabs(input[pos]) > env) {
	  env = fabs(input[pos]);
	} else {
	  env = fabs(input[pos]) * env_tr + env * (1.0f - env_tr);
	}
	if (env <= knee) {
	  env_sc = 1.0f / knee;
	} else {
	  env_sc = 1.0f / env;
	}
	buffer[buffer_pos] = input[pos];
	buffer_write(output[pos], buffer[(buffer_pos - delay) & BUFFER_MASK] * env_sc);
	buffer_pos = (buffer_pos + 1) & BUFFER_MASK;
      }

      plugin_data->env = env;
      plugin_data->buffer_pos = buffer_pos;
    ]]></callback>

    <port label="env_time_p" dir="input" type="control" hint="default_maximum">
      <name>Decay time (samples)</name>
      <p>Controls the envelope decay time.</p>
      <range min="2" max="30"/>
    </port>

    <port label="knee_point" dir="input" type="control" hint="default_0">
      <name>Knee point (dB)</name>
      <p>Controls the knee roll-off point, ie. the point above which the compression kicks in. 0 will have no effect, -90 will remove virtually all dynamic range.</p>
      <range min="-90" max="0"/>
    </port>

    <port label="input" dir="input" type="audio">
      <name>Input</name>
    </port>

    <port label="output" dir="output" type="audio">
      <name>Output</name>
    </port>

    <instance-data label="env" type="float" />
    <instance-data label="buffer" type="LADSPA_Data *" />
    <instance-data label="buffer_pos" type="unsigned int" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/ringmod_1188.xml
<?xml version="1.0" ?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css" ?>
<ladspa>
	<global>
		<meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
		<meta name="copyright" value="GPL"/>
		<meta name="properties" value="HARD_RT_CAPABLE"/>
		<code>
			#include "ladspa-util.h"

			int refcount;
			LADSPA_Data *sin_tbl, *tri_tbl, *saw_tbl, *squ_tbl;
			long sample_rate;
		</code>
	</global>

	<plugin label="ringmod_2i1o" id="1188" class="ModulatorPlugin">
		<name>Ringmod with two inputs</name>
		<p>This is a simple 2 input ring modulator.</p>
		<p>It is important that the modulator input is bounded to (-1, +1), otherwise you will get rubbish on the output.</p>

		<callback event="run">
			unsigned long pos;
			float tmpa = depth * 0.5f;
			float tmpb = 2.0f - depth;

			for (pos = 0; pos &lt; sample_count; pos++) {
				buffer_write(output[pos], input[pos] * (tmpa * modulator[pos] + tmpb));
			}
		</callback>

		<port label="depth" dir="input" type="control" hint="default_0">
			<name>Modulation depth (0=none, 1=AM, 2=RM)</name>
			<range min="0" max="2"/>
		</port>

		<port label="input" dir="input" type="audio">
			<name>Input</name>
			<p>This is the audio input.</p>
		</port>

		<port label="modulator" dir="input" type="audio" hint="default_0">
			<name>Modulator</name>
			<range min="-1" max="+1"/>
			<p>This is the modulator input.</p>
		</port>

		<port label="output" dir="output" type="audio">
			<name>Output</name>
		</port>
	</plugin>

	<plugin label="ringmod_1i1o1l" id="1189" class="ModulatorPlugin">
		<name>Ringmod with LFO</name>
		<p>This is a simple ring modulator and LFO.</p>

		<callback event="instantiate">
			long i;

			sample_rate = s_rate;

			if (refcount++ == 0) {
				sin_tbl = malloc(sizeof(LADSPA_Data) * sample_rate);
				for (i = 0; i &lt; sample_rate; i++) {
					sin_tbl[i] = sin(i * 2 * M_PI / sample_rate);
				}
				
				tri_tbl = malloc(sizeof(LADSPA_Data) * sample_rate);
				for (i = 0; i &lt; sample_rate; i++) {
					tri_tbl[i] = acos(cos(i * 2 * M_PI / sample_rate)) / M_PI * 2 - 1;
				}

				squ_tbl = malloc(sizeof(LADSPA_Data) * sample_rate);
				for (i = 0; i &lt; sample_rate; i++) {
					squ_tbl[i] = (i &lt; sample_rate/2) ? 1 : -1;
				}

				saw_tbl = malloc(sizeof(LADSPA_Data) * sample_rate);
				for (i = 0; i &lt; sample_rate; i++) {
					saw_tbl[i] = ((2.0 * i) - (float)sample_rate) / (float)sample_rate;
				}
			}

			offset = 0;
		</callback>

		<callback event="activate">
			offset = 0;
		</callback>

		<callback event="cleanup" unused-vars="plugin_data">
			if (--refcount == 0) {
				free(sin_tbl);
				free(tri_tbl);
				free(squ_tbl);
				free(saw_tbl);
			}
		</callback>

		<callback event="run">
			LADSPA_Data scale = fabs(sin) + fabs(tri) +
			 fabs(saw) + fabs(squ);
			int o;
			unsigned long pos;

			// Rescale to more useful value
			const float depth = depthp * 0.5f;

			if (scale == 0.0) {
				scale = 1.0;
			}

			for (pos = 0; pos &lt; sample_count; pos++) {
				o = f_round(offset);
				buffer_write(output[pos], input[pos] *
				 (depth * (((sin / scale) * sin_tbl[o]) +
				   ((tri / scale) * tri_tbl[o]) +
				   ((saw / scale) * saw_tbl[o]) +
				   ((squ / scale) * squ_tbl[o])) +
				   (1.0f - depth)));
				offset += freq;
				if (offset > sample_rate) {
					offset -= sample_rate;
				}
			}

			plugin_data->offset = offset;
		</callback>

		<port label="depthp" dir="input" type="control" hint="default_0">
			<name>Modulation depth (0=none, 1=AM, 2=RM)</name>
			<range min="0" max="2"/>
		</port>

		<port label="freq" dir="input" type="control" hint="default_440">
			<name>Frequency (Hz)</name>
			<range min="1" max="1000"/>
		</port>

		<port label="sin" dir="input" type="control" hint="default_1">
			<name>Sine level</name>
			<range min="-1" max="+1"/>
		</port>

		<port label="tri" dir="input" type="control" hint="default_0">
			<name>Triangle level</name>
			<range min="-1" max="+1"/>
		</port>

		<port label="saw" dir="input" type="control" hint="default_0">
			<name>Sawtooth level</name>
			<range min="-1" max="+1"/>
		</port>

		<port label="squ" dir="input" type="control" hint="default_0">
			<name>Square level</name>
			<range min="-1" max="+1"/>
		</port>

		<port label="input" dir="input" type="audio">
			<name>Input</name>
		</port>

		<port label="output" dir="output" type="audio">
			<name>Output</name>
		</port>

		<instance-data label="offset" type="LADSPA_Data"/>
	</plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/lookahead_limiter_1435.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code>
      #include "ladspa-util.h"
      #include "util/db.h"

      /* Minimum buffer size in seconds */
      #define BUFFER_TIME 2
    </code>
  </global>

  <plugin label="lookaheadLimiter" id="1435" class="LimiterPlugin">
    <name>Lookahead limiter</name>

    <callback event="instantiate"><![CDATA[
      buffer_len = 16384;
      buffer_pos = 0;
      fs = s_rate;

      db_init();

      /* Find size for power-of-two interleaved delay buffer */
      while(buffer_len < s_rate * BUFFER_TIME * 2) {
	buffer_len *= 2;
      }
      buffer = calloc(buffer_len, sizeof(float));

      peak = 0.0f;
      peak_dist = 1;
      atten = 0.0f;
    ]]></callback>

    <callback event="activate"><![CDATA[
      memset(buffer, 0, buffer_len * sizeof(float));

      peak = 0.0f;
      peak_dist = 1;
      atten = 0.0f;
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;
      const float max = DB_CO(limit);
      float sig, gain;
      const unsigned int delay = delay_s * fs;

      for (pos = 0; pos < sample_count; pos++) {
	buffer[(buffer_pos * 2) & (buffer_len - 1)] = in_1[pos];
	buffer[(buffer_pos * 2 + 1) & (buffer_len - 1)] = in_2[pos];

	/* sig contains the amplitude of the current frame, in dB's realtive
         * to the limit */
	sig = fabs(in_1[pos]) > fabs(in_2[pos]) ? fabs(in_1[pos]) :
		fabs(in_2[pos]);
        //sig = lin2db(sig) - limit;
        sig = CO_DB(sig) - limit;

	if (sig > 0.0f && sig / (float)delay > peak / (float)peak_dist) {
	  peak_dist = delay;
	  peak = sig;
	}

	/* Incremenatlly approach the correct attenuation for the next peak */
	atten -= (atten - peak) / (float)(peak_dist + 1);

	if (peak_dist-- == 0) {
		peak_dist = delay;
		peak = 0.0f;
	}

	gain = 1.0f / db2lin(atten);
	buffer_write(out_1[pos], buffer[(buffer_pos * 2 - delay * 2) &
					(buffer_len - 1)] * gain);
	buffer_write(out_2[pos], buffer[(buffer_pos * 2 - delay * 2 + 1) &
					(buffer_len - 1)] * gain);

	/* Ensure that the signal really can't be over the limit, potentially
         * changes in the lookahead time could cause us to miss peaks */

#if 0
XXX FIXME XXX
	if (out_1[pos] < -max) {
	  buffer_write(out_1[pos], -max);
	} else if (out_1[pos] > max) {
	  buffer_write(out_1[pos], max);
	}
	if (out_2[pos] < -max) {
	  buffer_write(out_2[pos], -max);
	} else if (out_2[pos] > max) {
	  buffer_write(out_2[pos], max);
	}
#endif

	buffer_pos++;
      }

      plugin_data->buffer_pos = buffer_pos;
      plugin_data->peak = peak;
      plugin_data->peak_dist = peak_dist;
      plugin_data->atten = atten;

      *(plugin_data->attenuation) = atten;
      *(plugin_data->latency) = delay;
    ]]></callback>

    <callback event="cleanup"><![CDATA[
       free(plugin_data->buffer);
    ]]></callback>

    <port label="limit" dir="input" type="control" hint="default_0">
      <name>Limit (dB)</name>
      <p>The maximum output amplitude. Peaks over this level will be attenuated as smoothly as possible to bring them as close as possible to this level.</p>
      <range min="-20" max="0"/>
    </port>

    <port label="delay_s" dir="input" type="control" hint="default_middle">
      <name>Lookahead delay</name>
      <p>The delay used by the lookahead predictor. The longer the delay the smoother the limiting will be, but higher the latency.</p>
      <range min="0.001" max="2.0"/>
    </port>

    <port label="attenuation" dir="output" type="control">
      <name>Attenuation (dB)</name>
      <p>The current attenuation of the signal coming out of the delay buffer.</p>
      <range min="0" max="12"/>
    </port>

    <port label="in_1" dir="input" type="audio">
      <name>Input 1</name>
    </port>

    <port label="in_2" dir="input" type="audio">
      <name>Input 2</name>
    </port>

    <port label="out_1" dir="output" type="audio">
      <name>Output 1</name>
    </port>

    <port label="out_2" dir="output" type="audio">
      <name>Output 2</name>
    </port>

    <port label="latency" dir="output" type="control">
      <name>latency</name>
    </port>

    <instance-data label="buffer" type="LADSPA_Data *" />
    <instance-data label="buffer_len" type="unsigned int" />
    <instance-data label="buffer_pos" type="unsigned int" />
    <instance-data label="fs" type="unsigned int" />
    <!-- running value for the attenuation -->
    <instance-data label="atten" type="float" />
    <!-- the next peak, relative to the limit -->
    <instance-data label="peak" type="float" />
    <!-- the number of sample until the next peak -->
    <instance-data label="peak_dist" type="unsigned int" />
  </plugin>
</ladspa>

=== LMMS/lmms/plugins/LadspaEffect/swh/upstream/sc4_1882.xml
<?xml version="1.0"?>
<!DOCTYPE ladspa SYSTEM "ladspa-swh.dtd">
<?xml-stylesheet href="ladspa.css" type="text/css"?>

<ladspa>
  <global>
    <meta name="maker" value="Steve Harris &lt;steve@plugin.org.uk&gt;"/>
    <meta name="copyright" value="GPL"/>
    <meta name="properties" value="HARD_RT_CAPABLE"/>
    <code><![CDATA[
      #include "util/db.h"
      #include "util/rms.h"

      #define A_TBL 256
    ]]></code>
  </global>

  <plugin label="sc4" id="1882" class="CompressorPlugin">
    <name>SC4</name>
    <p>A stereo compressor with variable envelope follower for RMS / peak behaviour. Based on the code for SC1.</p>

    <callback event="instantiate"><![CDATA[
      unsigned int i;
      float sample_rate = (float)s_rate;

      rms = rms_env_new();
      sum = 0.0f;
      amp = 0.0f;
      gain = 0.0f;
      gain_t = 0.0f;
      env = 0.0f;
      env_rms = 0.0f;
      env_peak = 0.0f;
      count = 0;

      as = malloc(A_TBL * sizeof(float));
      as[0] = 1.0f;
      for (i=1; i<A_TBL; i++) {
	as[i] = expf(-1.0f / (sample_rate * (float)i / (float)A_TBL));
      }

      db_init();
    ]]></callback>

    <callback event="cleanup"><![CDATA[
      rms_env_free(plugin_data->rms);
      free(plugin_data->as);
    ]]></callback>

    <callback event="run"><![CDATA[
      unsigned long pos;

      const float ga = attack < 2.0f ? 0.0f : as[f_round(attack * 0.001f * (float)(A_TBL-1))];
      const float gr = as[f_round(release * 0.001f * (float)(A_TBL-1))];
      const float rs = (ratio - 1.0f) / ratio;
      const float mug = db2lin(makeup_gain);
      const float knee_min = db2lin(threshold - knee);
      const float knee_max = db2lin(threshold + knee);
      const float ef_a = ga * 0.25f;
      const float ef_ai = 1.0f - ef_a;

      for (pos = 0; pos < sample_count; pos++) {
	const float la = fabs(left_in[pos]);
	const float ra = fabs(right_in[pos]);
	const float lev_in = f_max(la, ra);
        sum += lev_in * lev_in;

        if (amp > env_rms) {
          env_rms = env_rms * ga + amp * (1.0f - ga);
        } else {
          env_rms = env_rms * gr + amp * (1.0f - gr);
        }
	round_to_zero(&env_rms);
        if (lev_in > env_peak) {
          env_peak = env_peak * ga + lev_in * (1.0f - ga);
        } else {
          env_peak = env_peak * gr + lev_in * (1.0f - gr);
        }
	round_to_zero(&env_peak);
        if ((count++ & 3) == 3) {
          amp = rms_env_process(rms, sum * 0.25f);
          sum = 0.0f;
	  if (isnan(env_rms)) {
	    // This can happen sometimes, but I don't know why
	    env_rms = 0.0f;
	  }

          env = LIN_INTERP(rms_peak, env_rms, env_peak);

	  if (env <= knee_min) {
            gain_t = 1.0f;
	  } else if (env < knee_max) {
	    const float x = -(threshold - knee - lin2db(env)) / knee;
	    gain_t = db2lin(-knee * rs * x * x * 0.25f);
          } else {
            gain_t = db2lin((threshold - lin2db(env)) * rs);
          }
        }
        gain = gain * ef_a + gain_t * ef_ai;
        buffer_write(left_out[pos], left_in[pos] * gain * mug);
        buffer_write(right_out[pos], right_in[pos] * gain * mug);
      }
      plugin_data->sum = sum;
      plugin_data->amp = amp;
      plugin_data->gain = gain;
      plugin_data->gain_t = gain_t;
      plugin_data->env = env;
      plugin_data->env_rms = env_rms;
      plugin_data->env_peak = env_peak;
      plugin_data->count = count;

      *(plugin_data->amplitude) = lin2db(env);
      *(plugin_data->gain_red) = lin2db(gain);
    ]]></callback>

    <port label="rms_peak" dir="input" type="control" hint="default_minimum">
      <name>RMS/peak</name>
      <p>The balance between the RMS and peak envelope followers.</p>
      <p>RMS is generally better for subtle, musical compression and peak is better for heavier, fast compression and percussion.</p>
      <range min="0" max="1"/>
    </port>

    <port label="attack" dir="input" type="control" hint="default_low">
      <name>Attack time (ms)</name>
      <p>The attack time in milliseconds.</p>
      <range min="1.5" max="400"/>
    </port>

    <port label="release" dir="input" type="control" hint="default_middle">
      <name>Release time (ms)</name>
      <p>The release time in milliseconds.</p>
      <range min="2" max="800"/>
    </port>

    <port label="threshold" dir="input" type="control" hint="default_maximum">
      <name>Threshold level (dB)</name>
      <p>The point at which the compressor will start to kick in.</p>
      <range min="-30" max="0"/>
    </port>

    <port label="ratio" dir="input" type="control" hint="default_1">
      <name>Ratio (1:n)</name>
      <p>The gain reduction ratio used when the signal level exceeds the threshold.</p>
      <range min="1" max="20"/>
    </port>

    <port label="knee" dir="input" type="control" hint="default_low">
      <name>Knee radius (dB)</name>
      <p>The distance from the threshold where the knee curve starts.</p>
      <range min="1" max="10"/>
    </port>

    <port label="makeup_gain" dir="input" type="control" hint="default_0">
      <name>Makeup gain (dB)</name>
      <p>Controls the gain of the makeup input signal in dB's.</p>
      <range min="0" max="+24"/>
    </port>

    <port label="amplitude" dir="output" type="control">
      <name>Amplitude (dB)</name>
      <p>The level of the input signal, in decibels.</p>
      <range min="-40" max="+12"/>
    </port>

    <port label="gain_red" dir="output" type="control">
      <name>Gain reduction (dB)</name>
      <p>The degree of gain reduction applied to the input signal, in decibels.</p>
      <range min="-24" max="0"/>
    </port>

    <port label="left_in" dir="input" type="audio">
      <name>Left input</name>
    </port>

    <port label="right_in" dir="input" type="audio">
      <name>Right input</name>
    </port>

    <port label="left_out" dir="output" type="audio">
      <name>Left output</name>
    </port>

    <port label="right_out" dir="output" type="audio">
      <name>Right output</name>
    </port>

    <instance-data label="rms" type="rms_env *" />
    <instance-data label="as" type="float *" />

    <instance-data label="sum" type="float" />
    <instance-data label="amp" type="float" />
    <instance-data label="gain" type="float" />
    <instance-data label="gain_t" type="float" />
    <instance-data label="env" type="float" />
    <instance-data label="env_rms" type="float" />
    <instance-data label="env_peak" type="float" />
    <instance-data label="count" type="unsigned int" />
  </plugin>
</ladspa>
